### ISSUE TITLE
Broken links at end of setup-guide.md

### ISSUE THREAD

**Issue by s-ackroyd** [livewires/audio-production#1]
The 2 links at the end of https://github.com/livewires/audio-production/blob/master/setup-guide.md are broken.
I think they should link to
https://github.com/livewires/audio-production/blob/master/worksheets/00-intro-to-mixing.md
not 
https://github.com/livewires/audio-production/blob/master/00-intro-to-mixing.md
(i.e. need worksheets/ inserting in the links)

**Comment by clarkthomas4** [comment]
Thanks, fixed
